export const LOAD_INVOICES_LOADING = "LOAD_INVOICES_LOADING"
export const LOAD_INVOICES_SUCCESS = "LOAD_INVOICES_SUCCESS"
export const LOAD_INVOICES_ERROR = "LOAD_INVOICES_ERROR"
export const LOAD_INVOICE_DETAILS = "LOAD_INVOICE_DETAILS"