export const LOAD_INVOICES_LOADING = "LOAD_INVOICES_LOADING"
export const LOAD_INVOICES_SUCCESS = "LOAD_INVOICES_SUCCESS"
export const LOAD_INVOICES_ERROR = "LOAD_INVOICES_ERROR"
export const LOAD_INVOICE_DETAILS = "LOAD_INVOICE_DETAILS"
export const NEW_INVOICE_CREATE = "NEW_INVOICE_CREATE"
export const NEW_INVOICE_SAVE = "NEW_INVOICE_SAVE"

export const OPEN_SIDEBAR = "OPEN_SIDEBAR"
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR"
export const FETCH_SIDEBAR = "FETCH_SIDEBAR"

export const ADD_FORM_ADDITIONAL_PAYMENT = "ADD_FORM_ADDITIONAL_PAYMENT"
export const REMOVE_FORM_ADDITIONAL_PAYMENT = "REMOVE_FORM_ADDITIONAL_PAYMENT"
export const FETCH_FORM_ADDITIONAL_PAYMENTS = "FETCH_FORM_ADDITIONAL_PAYMENTS"